export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Home } from "./home/Home";
export { default as About } from "./about/About";
export { default as Contact } from "./contact/Contact";
export { default as HousrColiving } from "./category/housr-coliving";
export { default as HousrHomes } from "./category/housr-homes";
export { default as HousrStayAbode } from "./category/housr-stay-abode";
export { default as Partners } from "./partners/Partners";